using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocVault.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddIdentityAndOwnership : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── Documents.OwnerId ────────────────────────────────────────────────────
            // Use ADD COLUMN IF NOT EXISTS so the migration is safe to re-run when
            // EnsureCreated already created the column (e.g. from a dev iteration
            // that ran before this migration was generated).
            migrationBuilder.Sql("""
                ALTER TABLE "Documents"
                    ADD COLUMN IF NOT EXISTS "OwnerId" uuid;
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_Documents_OwnerId" ON "Documents" ("OwnerId");
                """);

            // ── ASP.NET Core Identity tables ─────────────────────────────────────────
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetRoles" (
                    "Id"               text                      NOT NULL,
                    "Name"             character varying(256)    NULL,
                    "NormalizedName"   character varying(256)    NULL,
                    "ConcurrencyStamp" text                      NULL,
                    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetUsers" (
                    "Id"                   text                      NOT NULL,
                    "DisplayName"          text                      NOT NULL DEFAULT '',
                    "IsGuest"              boolean                   NOT NULL DEFAULT false,
                    "CreatedAt"            timestamp with time zone  NOT NULL DEFAULT now(),
                    "UserName"             character varying(256)    NULL,
                    "NormalizedUserName"   character varying(256)    NULL,
                    "Email"                character varying(256)    NULL,
                    "NormalizedEmail"      character varying(256)    NULL,
                    "EmailConfirmed"       boolean                   NOT NULL,
                    "PasswordHash"         text                      NULL,
                    "SecurityStamp"        text                      NULL,
                    "ConcurrencyStamp"     text                      NULL,
                    "PhoneNumber"          text                      NULL,
                    "PhoneNumberConfirmed" boolean                   NOT NULL,
                    "TwoFactorEnabled"     boolean                   NOT NULL,
                    "LockoutEnd"           timestamp with time zone  NULL,
                    "LockoutEnabled"       boolean                   NOT NULL,
                    "AccessFailedCount"    integer                   NOT NULL,
                    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "RefreshTokens" (
                    "Id"        uuid                      NOT NULL,
                    "Token"     character varying(512)    NOT NULL,
                    "UserId"    text                      NOT NULL,
                    "ExpiresAt" timestamp with time zone  NOT NULL,
                    "CreatedAt" timestamp with time zone  NOT NULL DEFAULT now(),
                    "RevokedAt" timestamp with time zone  NULL,
                    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
                    "Id"         integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    "RoleId"     text     NOT NULL,
                    "ClaimType"  text     NULL,
                    "ClaimValue" text     NULL,
                    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
                        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
                    "Id"         integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    "UserId"     text     NOT NULL,
                    "ClaimType"  text     NULL,
                    "ClaimValue" text     NULL,
                    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
                    "LoginProvider"       text  NOT NULL,
                    "ProviderKey"         text  NOT NULL,
                    "ProviderDisplayName" text  NULL,
                    "UserId"              text  NOT NULL,
                    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
                    "UserId"  text  NOT NULL,
                    "RoleId"  text  NOT NULL,
                    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
                        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
                    "UserId"        text  NOT NULL,
                    "LoginProvider" text  NOT NULL,
                    "Name"          text  NOT NULL,
                    "Value"         text  NULL,
                    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
                        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );
                """);

            // ── Indexes (IF NOT EXISTS prevents duplicates on re-run) ────────────────
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");""");
            migrationBuilder.Sql("""CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");""");
            migrationBuilder.Sql("""CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;""");
            migrationBuilder.Sql("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "AspNetRoleClaims");
            migrationBuilder.DropTable(name: "AspNetUserClaims");
            migrationBuilder.DropTable(name: "AspNetUserLogins");
            migrationBuilder.DropTable(name: "AspNetUserRoles");
            migrationBuilder.DropTable(name: "AspNetUserTokens");
            migrationBuilder.DropTable(name: "RefreshTokens");
            migrationBuilder.DropTable(name: "AspNetRoles");
            migrationBuilder.DropTable(name: "AspNetUsers");

            migrationBuilder.DropIndex(name: "IX_Documents_OwnerId", table: "Documents");
            migrationBuilder.DropColumn(name: "OwnerId", table: "Documents");
        }
    }
}
